version: 0.0
os: windows
files:
  - source: \pipeline-to-pipeline.yaml
    destination: C:\Viewpost\AWSDeploy\Packages
hooks:
  BeforeInstall:
    - location: .\Install.ps1
      timeout: 900
  AfterInstall:
    - location: .\AfterInstall.ps1
      timeout: 180